//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.225
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dodoni.MathLibrary.GridPointCurves {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class CurveResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CurveResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Dodoni.MathLibrary.GridPointCurves.CurveResource", typeof(CurveResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string AnnotationBoundaryCubicSplineHaganWest {
            get {
                return ResourceManager.GetString("AnnotationBoundaryCubicSplineHaganWest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string AnnotationBoundaryCubicSplineHyman {
            get {
                return ResourceManager.GetString("AnnotationBoundaryCubicSplineHyman", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string AnnotationInterpolationCubicSplineMonotonicPre {
            get {
                return ResourceManager.GetString("AnnotationInterpolationCubicSplineMonotonicPre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string AnnotationParametrizationLeastSquares {
            get {
                return ResourceManager.GetString("AnnotationParametrizationLeastSquares", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hagan West Cubic spline boundary condition.
        /// </summary>
        internal static string LongNameBoundaryCubicSplineHaganWest {
            get {
                return ResourceManager.GetString("LongNameBoundaryCubicSplineHaganWest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hyman Cubic spline boundary condition.
        /// </summary>
        internal static string LongNameBoundaryCubicSplineHyman {
            get {
                return ResourceManager.GetString("LongNameBoundaryCubicSplineHyman", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monotonic preserving cubic spline interpolation.
        /// </summary>
        internal static string LongNameInterpolationCubicSplineMonotonicPre {
            get {
                return ResourceManager.GetString("LongNameInterpolationCubicSplineMonotonicPre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Least Squares Regression; Ordnung {0}.
        /// </summary>
        internal static string LongNameParametrizationLeastSquares {
            get {
                return ResourceManager.GetString("LongNameParametrizationLeastSquares", resourceCulture);
            }
        }
    }
}
