//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dodoni.BasicComponents {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ExceptionMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ExceptionMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Dodoni.BasicComponents.ExceptionMessages", typeof(ExceptionMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The input combination of {0} is not valid..
        /// </summary>
        public static string ArgumentCombinationInvalid {
            get {
                return ResourceManager.GetString("ArgumentCombinationInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} has a wrong dimension..
        /// </summary>
        public static string ArgumentHasWrongDimension {
            get {
                return ResourceManager.GetString("ArgumentHasWrongDimension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is +/-\infinity and not valid..
        /// </summary>
        public static string ArgumentIsInfinity {
            get {
                return ResourceManager.GetString("ArgumentIsInfinity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is an invalid input..
        /// </summary>
        public static string ArgumentIsInvalid {
            get {
                return ResourceManager.GetString("ArgumentIsInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is no valid input for {1}..
        /// </summary>
        public static string ArgumentIsInvalidForObject {
            get {
                return ResourceManager.GetString("ArgumentIsInvalidForObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is -\infinity and not valid..
        /// </summary>
        public static string ArgumentIsMinusInfinity {
            get {
                return ResourceManager.GetString("ArgumentIsMinusInfinity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is NaN (not a number) and not valid..
        /// </summary>
        public static string ArgumentIsNaN {
            get {
                return ResourceManager.GetString("ArgumentIsNaN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is not a squared matrix..
        /// </summary>
        public static string ArgumentIsNoSquaredMatrix {
            get {
                return ResourceManager.GetString("ArgumentIsNoSquaredMatrix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} contains non-valid data..
        /// </summary>
        public static string ArgumentIsNotWellDefined {
            get {
                return ResourceManager.GetString("ArgumentIsNotWellDefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is +\infinity and not valid..
        /// </summary>
        public static string ArgumentIsPositiveInfinity {
            get {
                return ResourceManager.GetString("ArgumentIsPositiveInfinity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is null reference..
        /// </summary>
        public static string ArgumentNull {
            get {
                return ResourceManager.GetString("ArgumentNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The argument {0} is outside the valid range {1}. .
        /// </summary>
        public static string ArgumentOutOfConstraint {
            get {
                return ResourceManager.GetString("ArgumentOutOfConstraint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The argument {0} is outside the valid range..
        /// </summary>
        public static string ArgumentOutOfRange {
            get {
                return ResourceManager.GetString("ArgumentOutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} must be greater than {1}..
        /// </summary>
        public static string ArgumentOutOfRangeGreater {
            get {
                return ResourceManager.GetString("ArgumentOutOfRangeGreater", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} must be greater than or equal {1}..
        /// </summary>
        public static string ArgumentOutOfRangeGreaterEqual {
            get {
                return ResourceManager.GetString("ArgumentOutOfRangeGreaterEqual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The argument {0} must be greater than or equal {1} and less than or equal {2}..
        /// </summary>
        public static string ArgumentOutOfRangeGreaterLessEqual {
            get {
                return ResourceManager.GetString("ArgumentOutOfRangeGreaterLessEqual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} must be less than or equal {1}..
        /// </summary>
        public static string ArgumentOutOfRangeLessEqual {
            get {
                return ResourceManager.GetString("ArgumentOutOfRangeLessEqual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The range between {0} and {1} must be less than or equal {2}..
        /// </summary>
        public static string ArgumentRangeLessEqual {
            get {
                return ResourceManager.GetString("ArgumentRangeLessEqual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No data given..
        /// </summary>
        public static string NoDataGiven {
            get {
                return ResourceManager.GetString("NoDataGiven", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is invalid for the given operation ({1})..
        /// </summary>
        public static string ObjectIsInvalid {
            get {
                return ResourceManager.GetString("ObjectIsInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is not operable..
        /// </summary>
        public static string ObjectIsNotOperable {
            get {
                return ResourceManager.GetString("ObjectIsNotOperable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is not ordered how the calling object assumes..
        /// </summary>
        public static string ObjectIsNotOrdered {
            get {
                return ResourceManager.GetString("ObjectIsNotOrdered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is read only..
        /// </summary>
        public static string ObjectIsReadOnly {
            get {
                return ResourceManager.GetString("ObjectIsReadOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The property group name {0} is unknown..
        /// </summary>
        public static string PropertyGroupNameUnknown {
            get {
                return ResourceManager.GetString("PropertyGroupNameUnknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The property name {0} is unknown..
        /// </summary>
        public static string PropertyNameUnknown {
            get {
                return ResourceManager.GetString("PropertyNameUnknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The table name {0} is unknown..
        /// </summary>
        public static string TableNameUnknown {
            get {
                return ResourceManager.GetString("TableNameUnknown", resourceCulture);
            }
        }
    }
}
