//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.225
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dodoni.MathLibrary.Miscellaneous {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class RoundingRuleNames {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RoundingRuleNames() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Dodoni.MathLibrary.Miscellaneous.RoundingRules.RoundingRuleNames", typeof(RoundingRuleNames).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bankers rounding ({0} fractional digits).
        /// </summary>
        internal static string BankersRounding {
            get {
                return ResourceManager.GetString("BankersRounding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ceiling rounding (unit {0}).
        /// </summary>
        internal static string CeilingRounding {
            get {
                return ResourceManager.GetString("CeilingRounding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Floor rounding (unit {0}).
        /// </summary>
        internal static string FloorRounding {
            get {
                return ResourceManager.GetString("FloorRounding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nearest integral value.
        /// </summary>
        internal static string NearestIntegralValueRounding {
            get {
                return ResourceManager.GetString("NearestIntegralValueRounding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No rounding.
        /// </summary>
        internal static string NoRounding {
            get {
                return ResourceManager.GetString("NoRounding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Truncation rounding ({0} fractional digits).
        /// </summary>
        internal static string TruncateRounding {
            get {
                return ResourceManager.GetString("TruncateRounding", resourceCulture);
            }
        }
    }
}
