//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.225
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dodoni.Finance.Compoundings {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class CompoundingResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CompoundingResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Dodoni.Finance.Compoundings.CompoundingResources", typeof(CompoundingResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The interest for an interest rate r and an interest period length t is equal to exp( r * t)..
        /// </summary>
        internal static string InterestContinuously {
            get {
                return ResourceManager.GetString("InterestContinuously", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The interest for an interest rate r and an interest period length t is equal to (1.0 + r/n)^(t * n) where n  = {0}..
        /// </summary>
        internal static string InterestPeriodic {
            get {
                return ResourceManager.GetString("InterestPeriodic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The interest for an interest rate r and an interest period length t is equal to (1.0 + r * t)..
        /// </summary>
        internal static string InterestSimple {
            get {
                return ResourceManager.GetString("InterestSimple", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The interest for an interest rate r and interest period length t is equal to (1 + r * t) if t*n &lt;= 1; otherwise (1.0 + r/n)^(t * n), where n = {0}..
        /// </summary>
        internal static string InterestSimpleThenPeriodic {
            get {
                return ResourceManager.GetString("InterestSimpleThenPeriodic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The time-t value of a zero-coupon bond with maturity T is represented by P(t,T) = exp( -(T-r) * r)..
        /// </summary>
        internal static string ZeroRateContinuously {
            get {
                return ResourceManager.GetString("ZeroRateContinuously", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The time-t value of a zero-coupon bond with maturity T is represented by P(t,T) = (1.0 + r/n)^(- (T-t) * n) where n  = {0}..
        /// </summary>
        internal static string ZeroRatePeriodic {
            get {
                return ResourceManager.GetString("ZeroRatePeriodic", resourceCulture);
            }
        }
    }
}
