//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dodoni.MathLibrary.Basics.LowLevel.Native {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class LapackResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LapackResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Dodoni.MathLibrary.Basics.LowLevel.Native.LapackResources", typeof(LapackResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use Lapack {0}, file name &quot;{1}&quot; with entry point nomenclature: &apos;{2}&apos;. .
        /// </summary>
        internal static string DescriptionLapack {
            get {
                return ResourceManager.GetString("DescriptionLapack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3.4.x.
        /// </summary>
        internal static string LapackVersion {
            get {
                return ResourceManager.GetString("LapackVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to lower case and underscore at the end of each function name.
        /// </summary>
        internal static string LowerCaseUnderscoreEntryPoints {
            get {
                return ResourceManager.GetString("LowerCaseUnderscoreEntryPoints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to upper case for each function name.
        /// </summary>
        internal static string UpperCaseEntryPoints {
            get {
                return ResourceManager.GetString("UpperCaseEntryPoints", resourceCulture);
            }
        }
    }
}
