//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.225
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dodoni.MathLibrary.GridPointCurves {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class CurveResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CurveResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Dodoni.MathLibrary.GridPointCurves.CurveResource", typeof(CurveResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string AnnotationBoundaryCubicSplineClamped {
            get {
                return ResourceManager.GetString("AnnotationBoundaryCubicSplineClamped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string AnnotationBoundaryCubicSplineNatural {
            get {
                return ResourceManager.GetString("AnnotationBoundaryCubicSplineNatural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Returns the value of the first grid point for the extrapolation beyond the first grid point..
        /// </summary>
        internal static string AnnotationExtrapolationConstantFirst {
            get {
                return ResourceManager.GetString("AnnotationExtrapolationConstantFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Returns {0} for the extrapolation beyond the first grid point..
        /// </summary>
        internal static string AnnotationExtrapolationConstantFirstIndividual {
            get {
                return ResourceManager.GetString("AnnotationExtrapolationConstantFirstIndividual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Returns the value of the last grid point for the extrapolation beyond the last grid point..
        /// </summary>
        internal static string AnnotationExtrapolationConstantLast {
            get {
                return ResourceManager.GetString("AnnotationExtrapolationConstantLast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply a constant extrapolation beyond the last grid point {0}.
        /// </summary>
        internal static string AnnotationExtrapolationConstantLastIndividual {
            get {
                return ResourceManager.GetString("AnnotationExtrapolationConstantLastIndividual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use a linear extrapolation beyond the first grid point, where the slope is specified as the derivative at the first grid point..
        /// </summary>
        internal static string AnnotationExtrapolationLinearFirstDifferentiable {
            get {
                return ResourceManager.GetString("AnnotationExtrapolationLinearFirstDifferentiable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use a linear extrapolation beyond the first grid point, where the slope is specified as {0}..
        /// </summary>
        internal static string AnnotationExtrapolationLinearFirstIndividual {
            get {
                return ResourceManager.GetString("AnnotationExtrapolationLinearFirstIndividual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use a linear extrapolation beyond the first grid point, where the slope is specified as the slope between the first two grid points..
        /// </summary>
        internal static string AnnotationExtrapolationLinearFirstTwoSlope {
            get {
                return ResourceManager.GetString("AnnotationExtrapolationLinearFirstTwoSlope", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use a linear extrapolation beyond the last grid point, where the slope is specified as the derivative at the last grid point..
        /// </summary>
        internal static string AnnotationExtrapolationLinearLastDifferentiable {
            get {
                return ResourceManager.GetString("AnnotationExtrapolationLinearLastDifferentiable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use a linear extrapolation beyond the last grid point, where the slope is specified as {0}..
        /// </summary>
        internal static string AnnotationExtrapolationLinearLastIndividual {
            get {
                return ResourceManager.GetString("AnnotationExtrapolationLinearLastIndividual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use a linear extrapolation beyond the last grid point, where the slope is  specified as the slope between the last two grid points..
        /// </summary>
        internal static string AnnotationExtrapolationLinearLastTwoSlope {
            get {
                return ResourceManager.GetString("AnnotationExtrapolationLinearLastTwoSlope", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do not apply any extrapolation beyond the first grid point. An exception will be thrown if one tries to access to a point beyond the first grid point..
        /// </summary>
        internal static string AnnotationExtrapolationNoneFirst {
            get {
                return ResourceManager.GetString("AnnotationExtrapolationNoneFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do not apply any extrapolation beyond the last grid point. An exception will be thrown if one tries to access to a point beyond the first grid point..
        /// </summary>
        internal static string AnnotationExtrapolationNoneLast {
            get {
                return ResourceManager.GetString("AnnotationExtrapolationNoneLast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Bessel method is an intermediate method, where the derivatives are estimated from the function values, and then the Hermite method is applied..
        /// </summary>
        internal static string AnnotationInterpolationBesselCubicSpline {
            get {
                return ResourceManager.GetString("AnnotationInterpolationBesselCubicSpline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply a cubic spline interpolation with a specific boundary condition. {0}.
        /// </summary>
        internal static string AnnotationInterpolationCubicSpline {
            get {
                return ResourceManager.GetString("AnnotationInterpolationCubicSpline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply a linear interpolation..
        /// </summary>
        internal static string AnnotationInterpolationLinear {
            get {
                return ResourceManager.GetString("AnnotationInterpolationLinear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply a log-linear interpolation, the value of each grid point must be positive..
        /// </summary>
        internal static string AnnotationInterpolationLogLinear {
            get {
                return ResourceManager.GetString("AnnotationInterpolationLogLinear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply a natural cubic spline interpolation, i.e. .
        /// </summary>
        internal static string AnnotationInterpolationNaturalCubicSpline {
            get {
                return ResourceManager.GetString("AnnotationInterpolationNaturalCubicSpline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do not apply any interpolation, throw an exception if one tries to acces to a point that is not a grid point..
        /// </summary>
        internal static string AnnotationInterpolationNone {
            get {
                return ResourceManager.GetString("AnnotationInterpolationNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Returns the left-end point of the sub-interval specified by the grid points..
        /// </summary>
        internal static string AnnotationInterpolationPiecewiseConstant {
            get {
                return ResourceManager.GetString("AnnotationInterpolationPiecewiseConstant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clamped cubic spline; y_0&apos;={0}; y_n&apos;={1}.
        /// </summary>
        internal static string LongNameBoundaryCubicSplineClamped {
            get {
                return ResourceManager.GetString("LongNameBoundaryCubicSplineClamped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Natural cubic spline boundary condition.
        /// </summary>
        internal static string LongNameBoundaryNaturalCubicSpline {
            get {
                return ResourceManager.GetString("LongNameBoundaryNaturalCubicSpline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First grid point constant extrapolation.
        /// </summary>
        internal static string LongNameExtrapolationConstantFirst {
            get {
                return ResourceManager.GetString("LongNameExtrapolationConstantFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Constant extrapolation beyond first grid point; {0}.
        /// </summary>
        internal static string LongNameExtrapolationConstantFirstIndividual {
            get {
                return ResourceManager.GetString("LongNameExtrapolationConstantFirstIndividual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Constant extrapolation beyond last grid point.
        /// </summary>
        internal static string LongNameExtrapolationConstantLast {
            get {
                return ResourceManager.GetString("LongNameExtrapolationConstantLast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Constant extrapolation beyond last grid point; {0}.
        /// </summary>
        internal static string LongNameExtrapolationConstantLastIndividual {
            get {
                return ResourceManager.GetString("LongNameExtrapolationConstantLastIndividual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Linear extrapolation beyond first differentiable grid point.
        /// </summary>
        internal static string LongNameExtrapolationLinearFirstDifferentiable {
            get {
                return ResourceManager.GetString("LongNameExtrapolationLinearFirstDifferentiable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Linear extrapolation beyond first grid point; slope ={0}.
        /// </summary>
        internal static string LongNameExtrapolationLinearFirstIndividual {
            get {
                return ResourceManager.GetString("LongNameExtrapolationLinearFirstIndividual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Linear extrapolation beyond first grid point; slope of first two grid points.
        /// </summary>
        internal static string LongNameExtrapolationLinearFirstTwoSlope {
            get {
                return ResourceManager.GetString("LongNameExtrapolationLinearFirstTwoSlope", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Linear extrapolation beyond last differentiable grid point.
        /// </summary>
        internal static string LongNameExtrapolationLinearLastDifferentiable {
            get {
                return ResourceManager.GetString("LongNameExtrapolationLinearLastDifferentiable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Linear extrapolation beyond last grid point; slope ={0}.
        /// </summary>
        internal static string LongNameExtrapolationLinearLastIndividual {
            get {
                return ResourceManager.GetString("LongNameExtrapolationLinearLastIndividual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Linear extrapolation beyond last grid point; slope of last two grid points.
        /// </summary>
        internal static string LongNameExtrapolationLinearLastTwoSlope {
            get {
                return ResourceManager.GetString("LongNameExtrapolationLinearLastTwoSlope", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No extrapolation beyond first grid point.
        /// </summary>
        internal static string LongNameExtrapolationNoneFirst {
            get {
                return ResourceManager.GetString("LongNameExtrapolationNoneFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No extrapolation beyond last grid point.
        /// </summary>
        internal static string LongNameExtrapolationNoneLast {
            get {
                return ResourceManager.GetString("LongNameExtrapolationNoneLast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bessel cubic spline interpolation.
        /// </summary>
        internal static string LongNameInterpolationBesselCubicSpline {
            get {
                return ResourceManager.GetString("LongNameInterpolationBesselCubicSpline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cubic spline interpolation.
        /// </summary>
        internal static string LongNameInterpolationCubicSpline {
            get {
                return ResourceManager.GetString("LongNameInterpolationCubicSpline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Linear interpolation.
        /// </summary>
        internal static string LongNameInterpolationLinear {
            get {
                return ResourceManager.GetString("LongNameInterpolationLinear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log-Linear interpolation.
        /// </summary>
        internal static string LongNameInterpolationLogLinear {
            get {
                return ResourceManager.GetString("LongNameInterpolationLogLinear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Natural cubic spline interpolation.
        /// </summary>
        internal static string LongNameInterpolationNaturalCubicSpline {
            get {
                return ResourceManager.GetString("LongNameInterpolationNaturalCubicSpline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No interpolation.
        /// </summary>
        internal static string LongNameInterpolationNone {
            get {
                return ResourceManager.GetString("LongNameInterpolationNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Piecewise constant interpolation.
        /// </summary>
        internal static string LongNameInterpolationPiecewiseConstant {
            get {
                return ResourceManager.GetString("LongNameInterpolationPiecewiseConstant", resourceCulture);
            }
        }
    }
}
