//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dodoni.Finance.CommonMarketUsages.HolidayCalendars {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Dodoni.Finance.CommonMarketUsages.HolidayCalendars.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Each day is a business day..
        /// </summary>
        internal static string EmptyCalendarDescription {
            get {
                return ResourceManager.GetString("EmptyCalendarDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No day is a weekend day..
        /// </summary>
        internal static string EmptyWeekendType {
            get {
                return ResourceManager.GetString("EmptyWeekendType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The weekend consists of {0}..
        /// </summary>
        internal static string GenericWeekendType {
            get {
                return ResourceManager.GetString("GenericWeekendType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Joint by business calendar of the following holiday calendar {0}..
        /// </summary>
        internal static string JointBusinessCalendarDescription {
            get {
                return ResourceManager.GetString("JointBusinessCalendarDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Join by holiday calendar of the following holiday calendar {0}..
        /// </summary>
        internal static string JointHolidayCalendarDescription {
            get {
                return ResourceManager.GetString("JointHolidayCalendarDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The weekend consists of Saturdays and Sundays. .
        /// </summary>
        internal static string StandardWeekendType {
            get {
                return ResourceManager.GetString("StandardWeekendType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Each day is some business day, except Saturdays and sundays. .
        /// </summary>
        internal static string WeekendCalendarDescription {
            get {
                return ResourceManager.GetString("WeekendCalendarDescription", resourceCulture);
            }
        }
    }
}
