//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.225
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dodoni.MathLibrary.Surfaces.MissingValueReplenishments {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class MissingValueReplenishmentResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MissingValueReplenishmentResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Dodoni.MathLibrary.Surfaces.MissingValueReplenishments.MissingValueReplenishmentR" +
                            "esource", typeof(MissingValueReplenishmentResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply a interpolation/parametrization along horizontal direction to fill missing values..
        /// </summary>
        internal static string AnnotationAlongXAxis {
            get {
                return ResourceManager.GetString("AnnotationAlongXAxis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply a interpolation/parametrization along vertical direction to fill missing values..
        /// </summary>
        internal static string AnnotationAlongYAxis {
            get {
                return ResourceManager.GetString("AnnotationAlongYAxis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply a weighted interpolation/parametrization along horizontal and vertical direction to fill missing values..
        /// </summary>
        internal static string AnnotationNearestWeighted {
            get {
                return ResourceManager.GetString("AnnotationNearestWeighted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do not fill missing values..
        /// </summary>
        internal static string AnnotationNone {
            get {
                return ResourceManager.GetString("AnnotationNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Horizontal Missing Value Replenishment.
        /// </summary>
        internal static string LongNameAlongXAxis {
            get {
                return ResourceManager.GetString("LongNameAlongXAxis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vertical Missing Value Replenishment.
        /// </summary>
        internal static string LongNameAlongYAxis {
            get {
                return ResourceManager.GetString("LongNameAlongYAxis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weighted Missing Value Replenishment: horizontal {0}, vertical {1}, weight {2}.
        /// </summary>
        internal static string LongNameNearestWeighted {
            get {
                return ResourceManager.GetString("LongNameNearestWeighted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None Missing Value Replenishment.
        /// </summary>
        internal static string LongNameNone {
            get {
                return ResourceManager.GetString("LongNameNone", resourceCulture);
            }
        }
    }
}
