//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.225
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dodoni.BasicComponents.Logging {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class LoggingResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LoggingResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Dodoni.BasicComponents.Logging.LoggingResources", typeof(LoggingResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A generic Error message..
        /// </summary>
        internal static string AnnotationErrorMessageType {
            get {
                return ResourceManager.GetString("AnnotationErrorMessageType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A generic Fatal Error message..
        /// </summary>
        internal static string AnnotationFatalErrorMessageType {
            get {
                return ResourceManager.GetString("AnnotationFatalErrorMessageType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A generic Info message..
        /// </summary>
        internal static string AnnotationInfoMessageType {
            get {
                return ResourceManager.GetString("AnnotationInfoMessageType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A specific Item has been added to a specified pool of objects..
        /// </summary>
        internal static string AnnotationPoolItemAddedInfoMessageType {
            get {
                return ResourceManager.GetString("AnnotationPoolItemAddedInfoMessageType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A specific Item in a specified pool of objects has been replaced..
        /// </summary>
        internal static string AnnotationPoolItemReplacedInfoMessageType {
            get {
                return ResourceManager.GetString("AnnotationPoolItemReplacedInfoMessageType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A generic Warning message..
        /// </summary>
        internal static string AnnotationWarningMessageType {
            get {
                return ResourceManager.GetString("AnnotationWarningMessageType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string LongNameErrorMessageType {
            get {
                return ResourceManager.GetString("LongNameErrorMessageType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fatal error.
        /// </summary>
        internal static string LongNameFatalErrorMessageType {
            get {
                return ResourceManager.GetString("LongNameFatalErrorMessageType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Info.
        /// </summary>
        internal static string LongNameInfoMessageType {
            get {
                return ResourceManager.GetString("LongNameInfoMessageType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pool Item added.
        /// </summary>
        internal static string LongNamePoolItemAddedInfoMessageType {
            get {
                return ResourceManager.GetString("LongNamePoolItemAddedInfoMessageType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pool Item replaced.
        /// </summary>
        internal static string LongNamePoolItemReplacedInfoMessageType {
            get {
                return ResourceManager.GetString("LongNamePoolItemReplacedInfoMessageType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        internal static string LongNameWarningMessageType {
            get {
                return ResourceManager.GetString("LongNameWarningMessageType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknow.
        /// </summary>
        internal static string Unknow {
            get {
                return ResourceManager.GetString("Unknow", resourceCulture);
            }
        }
    }
}
