//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dodoni.Finance.DateFactory {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class DateFactoryResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DateFactoryResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Dodoni.Finance.DateFactory.DateFactoryResources", typeof(DateFactoryResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The time span is one year, i.e. roll the date every year..
        /// </summary>
        internal static string Annually {
            get {
                return ResourceManager.GetString("Annually", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to annually.
        /// </summary>
        internal static string AnnuallyLongName {
            get {
                return ResourceManager.GetString("AnnuallyLongName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The time span is two month, i.e. roll the date every second month..
        /// </summary>
        internal static string BiMonthly {
            get {
                return ResourceManager.GetString("BiMonthly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bi-monthly.
        /// </summary>
        internal static string BiMonthlyLongName {
            get {
                return ResourceManager.GetString("BiMonthlyLongName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The time span is one day, i.e. roll the date daily..
        /// </summary>
        internal static string Daily {
            get {
                return ResourceManager.GetString("Daily", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to daily.
        /// </summary>
        internal static string DailyLongName {
            get {
                return ResourceManager.GetString("DailyLongName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The time span is equal to four weeks..
        /// </summary>
        internal static string EveryFourWeeks {
            get {
                return ResourceManager.GetString("EveryFourWeeks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Every four week frequency.
        /// </summary>
        internal static string EveryFourWeeksLongName {
            get {
                return ResourceManager.GetString("EveryFourWeeksLongName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The first date ({0}) to add into a specific date schedule..
        /// </summary>
        internal static string FirstDate {
            get {
                return ResourceManager.GetString("FirstDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to first regular date {0}.
        /// </summary>
        internal static string FirstRegularDate {
            get {
                return ResourceManager.GetString("FirstRegularDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to frequency {0}.
        /// </summary>
        internal static string Frequency {
            get {
                return ResourceManager.GetString("Frequency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A user defined date schedule frequency..
        /// </summary>
        internal static string Individual {
            get {
                return ResourceManager.GetString("Individual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Individual date schedule frequency with period length {0}..
        /// </summary>
        internal static string IndividualLongName {
            get {
                return ResourceManager.GetString("IndividualLongName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to last regular date {0}.
        /// </summary>
        internal static string LastRegularDate {
            get {
                return ResourceManager.GetString("LastRegularDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The time span is one month, i.e. roll the date every month..
        /// </summary>
        internal static string Monthly {
            get {
                return ResourceManager.GetString("Monthly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to monthly.
        /// </summary>
        internal static string MonthlyLongName {
            get {
                return ResourceManager.GetString("MonthlyLongName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One regular period only..
        /// </summary>
        internal static string Once {
            get {
                return ResourceManager.GetString("Once", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to once.
        /// </summary>
        internal static string OnceLongName {
            get {
                return ResourceManager.GetString("OnceLongName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The time span is three months, i.e. roll the date every three months..
        /// </summary>
        internal static string Quarterly {
            get {
                return ResourceManager.GetString("Quarterly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to quarterly.
        /// </summary>
        internal static string QuarterlyLongName {
            get {
                return ResourceManager.GetString("QuarterlyLongName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to seed business day convention {0}.
        /// </summary>
        internal static string SeedBusinessDayConvention {
            get {
                return ResourceManager.GetString("SeedBusinessDayConvention", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The time span is a half year, i.e. roll the date every six month..
        /// </summary>
        internal static string SemiAnnually {
            get {
                return ResourceManager.GetString("SemiAnnually", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to semi annually.
        /// </summary>
        internal static string SemiAnnuallyLongName {
            get {
                return ResourceManager.GetString("SemiAnnuallyLongName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to termination date {0}.
        /// </summary>
        internal static string TerminationDate {
            get {
                return ResourceManager.GetString("TerminationDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A weekly date schedule frequency..
        /// </summary>
        internal static string Weekly {
            get {
                return ResourceManager.GetString("Weekly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to weekly.
        /// </summary>
        internal static string WeeklyLongName {
            get {
                return ResourceManager.GetString("WeeklyLongName", resourceCulture);
            }
        }
    }
}
